CREATE TABLE COUNTRY (
  cn_id INTEGER NOT NULL,
  cn_code CHAR(2) NULL,
  cn_name VARCHAR(40) NULL,
  PRIMARY KEY(cn_id)
);

CREATE TABLE AIRPORT (
  ap_id INTEGER NOT NULL,
  ap_name VARCHAR(40) NULL,
  cn_id INTEGER NOT NULL,
  PRIMARY KEY(ap_id),
  FOREIGN KEY(cn_id)
    REFERENCES COUNTRY(cn_id)
);

CREATE TABLE EMPLOYEE (
  emp_id INTEGER NOT NULL,
  emp_surname VARCHAR(40) NULL,
  emp_firstname VARCHAR(40) NULL,
  cn_id INTEGER NOT NULL,
  PRIMARY KEY(emp_id),
  FOREIGN KEY(cn_id)
    REFERENCES COUNTRY(cn_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE SPOKEN_LANGUAGE (
  lan_id INTEGER NOT NULL,
  lan_code CHAR(2) NULL,
  lan_name VARCHAR(40) NULL,
  PRIMARY KEY(lan_id)
);

CREATE TABLE EMPLOYEE_SPEAKS_LANGUAGE (
  emp_id INTEGER NOT NULL,
  lan_id INTEGER NOT NULL,
  FOREIGN KEY(emp_id)
    REFERENCES EMPLOYEE(emp_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(lan_id)
    REFERENCES SPOKEN_LANGUAGE(lan_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);
